export const initialState = {
	processing: false,
	url: '',
	books: [],
	numberOfBooks: 0,
	processingLanguages: false,
	languages: [],
	processingRatings: false,
	ratings: [],
	editingMode: false,
	currentBook: {},
}

export const types = {
	GET_BOOKS_START: 'GET_BOOKS_START',
	GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
	GET_BOOKS_FAILURE: 'GET_BOOKS_FAILURE',

	GET_CURRENT_BOOK_START: 'GET_CURRENT_BOOK_START',
	GET_CURRENT_BOOK_SUCCESS: 'GET_CURRENT_BOOK_SUCCESS',
	GET_CURRENT_BOOK_FAILURE: 'GET_CURRENT_BOOK_FAILURE',

	GET_LANGUAGES_START: 'GET_LANGUAGES_START',
	GET_LANGUAGES_SUCCESS: 'GET_LANGUAGES_SUCCESS',
	GET_LANGUAGES_FAILURE: 'GET_LANGUAGES_FAILURE',

	GET_RATINGS_START: 'GET_RATINGS_START',
	GET_RATINGS_SUCCESS: 'GET_RATINGS_SUCCESS',
	GET_RATINGS_FAILURE: 'GET_RATINGS_FAILURE',

	EDIT_BOOK_START: 'EDIT_BOOK_START',
	EDIT_BOOK_SUCCESS: 'EDIT_BOOK_SUCCESS',
	EDIT_BOOK_FAILURE: 'EDIT_BOOK_FAILURE',

	SET_EDITING_MODE: 'SET_EDITING_MODE',

	DELETE_BOOK_START: 'DELETE_BOOK_START',
	DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
	DELETE_BOOK_FAILURE: 'DELETE_BOOK_FAILURE',

	ADD_BOOK_START: 'ADD_BOOK_START',
	ADD_BOOK_SUCCESS: 'ADD_BOOK_SUCCESS',
	ADD_BOOK_FAILURE: 'ADD_BOOK_FAILURE',

	CLEAR_CURRENT_BOOK: 'CLEAR_CURRENT_BOOK',

	BUY_BOOKS_START: 'BUY_BOOKS_START',
	BUY_BOOKS_SUCCESS: 'BUY_BOOKS_SUCCESS',
	BUY_BOOKS_FAILURE: 'BUY_BOOKS_FAILURE',
}

export * from './actions'
export * from './sagas'

export default (state = initialState, action) => action.type in types ? { ...state, ...action.payload, } : state